# Set parameters for feature extraction

imageType:
  Original: {}
  # LoG:  
  #   sigma: [1, 3, 5]
  # Exponential: {}
  # Logarithm: {}
  # Gradient: {}  
  # Wavelet: {}
  # Square: {}
  # SquareRoot: {}
  # LBP2D: {}

# featureClass: #By default, all features are enabled


setting:
  label: 255
  
  # Normalization
  normalize: True
  normalizeScale: 100

  # Resampling
  interpolator: 'sitkBSpline'
  resampledPixelSpacing: [2, 2, 0] # change to 2d: [2,2] for gray scale images

  # PreCrop Setting preCrop to true speeds up extraction and makes it less memory intensive
  # padDistance: 10  
  # preCrop: True

  # Probably not needed if input mask is in 2D
  # force2D: True
  # force2Ddimension: 0

  # Gray scale discretization
  binWidth: 5 # This parameter should be estimated by analyzing the dataset firstorder range and chosen to be as close as possible to the 30-130 range. 

  # Shift to make sure all values are positive
  voxelArrayShift: 300
