# Set parameters for feature extraction

imageType:
  Original: {}
  LoG:  
    sigma: [1, 3, 5]
  Exponential: {}
  Logarithm: {}
  Gradient: {}  
  Wavelet: {}
  Square: {}
  SquareRoot: {}
  LBP2D: {}
  LBP3D: {}

featureClass:
  # This is all features except shape2D
  firstorder:
  shape:
  glcm: [ # All glcm features except JointAverage
    'Autocorrelation', 
    'ClusterProminence', 
    'ClusterShade', 
    'ClusterTendency', 
    'Contrast', 
    'Correlation', 
    'DifferenceAverage', 
    'DifferenceEntropy', 
    'DifferenceVariance', 
    'Id', 
    'Idm', 
    'Idmn', 
    'Idn', 
    'Imc1', 
    'Imc2', 
    'InverseVariance', 
    'JointEnergy',  
    'JointEntropy', 
    'MCC', 
    'MaximumProbability',  
    'SumAverage', 
    'SumEntropy', 
    'SumSquares'
    ]
  glrlm:
  glszm:
  gldm:
  ngtdm:


setting:
  label: 255
  
  # Enable normalization
  normalize: True
  normalizeScale: 100

  # Enable resampling
  interpolator: 'sitkBSpline'
  resampledPixelSpacing: [0.5, 0.5, 0] # Resample only in x-, and y-direction (i.e. not along the axis perpendicular to the tiff-images)

  # Extract features from an image layer by layer, the feature values are aggregated to one combined value for all layers
  force2D: True
  force2Ddimension: 0

  # Gray scale discretization
  binWidth: 5 

  # Shift to make sure all values are positive
  voxelArrayShift: 300
